config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :customers
    resources :part_types
    resources :car_parts
  end

  devise_for :admins, controllers: {
    registrations: "devise_admin/registrations"
  }
  devise_for :customers

  get "home", to: "home#index"
  get "admin", to: "admin#index"

  root "home#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car_part.rb
class CarPart < ApplicationRecord
  belongs_to :part_type
  has_one_attached :image do |attachable|
    attachable.variant :small, resize_to_limit: [ 50, 50 ]
    attachable.variant :medium, resize_to_limit: [ 200, 200 ]
    attachable.variant :large, resize_to_limit: [ 500, 500 ]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/part_type.rb
class PartType < ApplicationRecord
  has_many :car_parts, dependent: :destroy
  has_one_attached :image do |attachable|
    attachable.variant :small, resize_to_limit: [ 50, 50 ]
    attachable.variant :medium, resize_to_limit: [ 200, 200 ]
    attachable.variant :large, resize_to_limit: [ 500, 500 ]
  end
end

app/controllers/admin/car_parts_controller.rb
class Admin::CarPartsController < AdminController
  before_action :set_car_part, only: %i[ show destroy ]
  def index
    @pagy, @car_parts = pagy(CarPart.all)
  end

  def show
  end

  def destroy
    @car_part.destroy!

    redirect_to admin_car_parts_path, notice: "Car part was seccessfully destroyed."
  end

  private
    def set_car_part
      @car_part = CarPart.find(params.expect(:id))
    end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < AdminController
  before_action :set_customer, only: %i[ show destroy ]
  def index
    @pagy, @customers = pagy(Customer.all)
  end

  def show
  end

  def destroy
    @customer.destroy!

    redirect_to admin_customers_path, notice: "customer was seccessfully destroyed."
  end

  private
    def set_customer
      @customer = Customer.find(params.expect(:id))
    end
end

app/controllers/admin/part_types_controller.rb
class Admin::PartTypesController < AdminController
  before_action :set_part_type, only: %i[ show edit update destroy ]
  def index
    @pagy, @part_types = pagy(PartType.all)
  end

  def show
  end

  def new
    @part_type = PartType.new
  end

  def edit
  end

  def create
    @part_type = PartType.new(part_type_params)

    if @part_type.save
      redirect_to admin_part_type_path(@part_type), notice: "Part type successfully created."
    else
      render :new, alert: "Error when craeting part type"
    end
  end

  def update
    if @part_type.update(part_type_params)
      redirect_to admin_part_type_path(@part_type), notice: "Part type successfully updated."
    else
      render :edit, alert: "Error when updating part type"
    end
  end

  def destroy
    @part_type.destroy!

    redirect_to admin_part_types_path, notice: "Part type was seccessfully destroyed."
  end

  private
    def set_part_type
      @part_type = PartType.find(params.expect(:id))
    end

    def part_type_params
      params.expect(part_type: [ :name, :description, :image ])
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  allow_browser versions: :modern
end

app/controllers/devise_admin/registrations_controller.rb
# frozen_string_literal: true

class DeviseAdmin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  layout "admin"

  # GET /resource/sign_up
  def new
    redirect_to admin_path, alert: "Admin can't sign up"
  end

  # POST /resource
  def create
    redirect_to admin_path, alert: "Can't create admin"
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if admin_signed_in?
      redirect_to admin_path
    end
  end
end

app/helpers/admin/car_parts_helper.rb
module Admin::CarPartsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/part_types_helper.rb
module Admin::PartTypesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/car_parts/index.html.erb
<div class="card shadow-sm">
  <div class="card-body">
    <div class="p-3">
      <h2 class="display-6">Car parts</h2>
    </div>
    <div class="mt-2">
      <table class="table table-hover border-top">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Price</th>
            <th>Active</th>
            <th>Type</th>
            <th>Created</th>
            <th>Last Updated</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @car_parts.each do |car_part| %>
            <tr>
              <td style="width: 50px; height: 50px;" class="p-0 text-center align-middle">
                <%= car_part.image.present? ? image_tag(car_part.image.variant(:small)) : image_tag("https://via.placeholder.com/50") %></td>
              <td><%= car_part.name %></td>
              <td><%= car_part.price %> €</td>
              <td><%= car_part.active %></td>
              <td><%= car_part.part_type.name %></td>
              <td><%= car_part.created_at.strftime("%Y-%m-%d %H:%M") %></td>
              <td><%= car_part.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
              <td><%= link_to "view", admin_car_part_path(car_part), class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= render "layouts/pagination", pagy: @pagy %>
    </div>
  </div>
</div>

app/views/admin/car_parts/show.html.erb
<div>
  <%= link_to "back", admin_car_parts_path, class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
  <div class="card shadow-sm mt-3">
    <div class="card-body">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="display-6">Show Car Part</h2>
        <div class="d-flex">
          <div class="mx-1">
            <%= button_to "Delete", admin_car_part_path(@car_part), method: :delete, data: {turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5 d-flex justify-content-center mb-4">
          <%= @car_part.image.present? ? image_tag(@car_part.image.variant(:large), class: "img-fluid rounded shadow") : image_tag("https://via.placeholder.com/500", class: "img-fluid rounded shadow") %>
        </div>
        <div class="col-md-7">
          <div class="card shadow-sm">
            <div class="card-body">
              <h5 class="card-title">Car Part Details</h5>
              <p class="mb-2"><strong>Name</strong> <%= @car_part.name %></p>
              <p class="mb-2"><strong>Price</strong> <%= @car_part.price %> €</p>
              <p class="mb-2"><strong>Active</strong> <%= @car_part.active %></p>
              <p class="mb-2"><strong>Type</strong> <%= @car_part.part_type.name %></p>
              <p class="mb-2"><strong>Created</strong> <%= @car_part.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              <p class="mb-2"><strong>Last updated</strong> <%= @car_part.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
              <div>
                <p class="mb-0"><strong>Description</strong></p>
                <p class="mt-0"><%= @car_part.description %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="card shadow-sm">
  <div class="card-body">
    <div class="p-3">
      <h2 class="display-6">Customers</h2>
    </div>
    <div class="mt-2">
      <table class="table table-hover border-top">
        <thead>
          <tr>
            <th>Email</th>
            <th>Created</th>
            <th>Last Updated</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.email %></td>
              <td><%= customer.created_at.strftime("%Y-%m-%d %H:%M") %></td>
              <td><%= customer.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
              <td><%= link_to "view", admin_customer_path(customer), class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= render "layouts/pagination", pagy: @pagy %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div>
  <%= link_to "back", admin_customers_path, class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
  <div class="card shadow-sm mt-3">
    <div class="card-body">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="display-6">Show Customer</h2>
        <%= button_to "Delete", admin_customer_path(@customer), method: :delete, data: {turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
      </div>
      <div>
        <h5 class="card-title">Customer Details</h5>
        <p class="mb-2"><strong>Email</strong> <%= @customer.email %></p>
        <p class="mb-2"><strong>Created</strong> <%= @customer.created_at.strftime("%Y-%m-%d %H:%M") %></p>
        <p class="mb-2"><strong>Last updated</strong> <%= @customer.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
      </div>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/admin/part_types/_form.html.erb
<%= form_with(model: [:admin, part_type]) do |form| %>
  <% if part_type.errors.any? %>
    <ul>
      <% part_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="field my-1">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="field my-1">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, rows: 8, class: "form-control" %>
  </div>
  <div class="field my-1">
    <div class="row">
      <div class="col-md-6 d-flex justify-content-center align-items-center" style="width: 200px; height: 200px;">
        <div class="d-flex justify-content-center align-items-center w-100 h-100">
          <%= part_type.image.present? ? image_tag(part_type.image.variant(resize_to_limit: [200, 200]), id: "image-preview", class: "img-fluid") : image_tag("https://via.placeholder.com/200", id: "image-preview", class: "img-fluid") %>
        </div>
      </div>
      <div class="col-md my-auto">
        <%= form.label :image, class: "form-label" %>
        <%= form.file_field :image, class: "form-control", id: "image-input" %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-end">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const imageInput = document.getElementById("image-input");
    const imagePreview = document.getElementById("image-preview");

    imageInput.addEventListener("change", function(event) {
      const file = event.target.files[0];
      if (file) {
        const reader = new FileReader();
        reader.onload = function(e) {
          const img = new Image();
          img.onload = function() {
            const maxWidth = 200;
            const maxHeight = 200;

            let width = img.width;
            let height = img.height;

            if (width > maxWidth || height > maxHeight) {
              if (width > height) {
                height *= maxWidth / width;
                width = maxWidth;
              } else {
                width *= maxHeight / height;
                height = maxHeight;
              }
            }

            imagePreview.src = e.target.result;
            imagePreview.style.width = `${width}px`;
            imagePreview.style.height = `${height}px`;
          };
          img.src = e.target.result;
        };
        reader.readAsDataURL(file);
      }
    });
  });
</script>

app/views/admin/part_types/edit.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <%= link_to "back", admin_part_type_path(@part_type), class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
    <div class="card shadow-sm mt-3">
      <div class="card-body">
        <h3 class="mb-4 text-center">Edit part type</h3>
        <%= render "form", part_type: @part_type %>
      </div>
    </div>
  </div>
</div>

app/views/admin/part_types/index.html.erb
<div class="card shadow-sm">
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center p-3">
      <h2 class="display-6">Part Types</h2>
      <%= link_to "New Part Type", new_admin_part_type_path, class: "btn btn-primary" %>
    </div>
    <div class="mt-2">
      <table class="table table-hover border-top">
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Created</th>
            <th>Last Updated</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @part_types.each do |part_type| %>
            <tr>
              <td style="width: 50px; height: 50px;" class="p-0 text-center align-middle">
                <%= part_type.image.present? ? image_tag(part_type.image.variant(:small)) : image_tag("https://via.placeholder.com/50") %></td>
              <td><%= part_type.name %></td>
              <td><%= part_type.created_at.strftime("%Y-%m-%d %H:%M") %></td>
              <td><%= part_type.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
              <td><%= link_to "view", admin_part_type_path(part_type), class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= render "layouts/pagination", pagy: @pagy %>
    </div>
  </div>
</div>

app/views/admin/part_types/new.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <%= link_to "back", admin_part_types_path, class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
    <div class="card shadow-sm mt-3">
      <div class="card-body">
        <h3 class="mb-4 text-center">New part type</h3>
        <%= render "form", part_type: @part_type %>
      </div>
    </div>
  </div>
</div>

app/views/admin/part_types/show.html.erb
<div>
  <%= link_to "back", admin_part_types_path, class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
  <div class="card shadow-sm mt-3">
    <div class="card-body">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="display-6">Show Part Type</h2>
        <div class="d-flex">
          <div class="mx-1">
            <%= link_to "Edit", edit_admin_part_type_path(@part_type), class: "btn btn-primary" %>
          </div>
          <div class="mx-1">
            <%= button_to "Delete", admin_part_type_path(@part_type), method: :delete, data: {turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5 d-flex justify-content-center mb-4">
          <%= @part_type.image.present? ? image_tag(@part_type.image.variant(:large), class: "img-fluid rounded shadow") : image_tag("https://via.placeholder.com/500", class: "img-fluid rounded shadow") %>
        </div>
        <div class="col-md-7">
          <div class="card shadow-sm">
            <div class="card-body">
              <h5 class="card-title">Part Type Details</h5>
              <p class="mb-2"><strong>Name</strong> <%= @part_type.name %></p>
              <p class="mb-2"><strong>Created</strong> <%= @part_type.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              <p class="mb-2"><strong>Last updated</strong> <%= @part_type.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
              <div>
                <p class="mb-0"><strong>Description</strong></p>
                <p class="mt-0"><%= @part_type.description %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div>
  <h2>Home page</h2>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris gravida massa quis ultricies scelerisque. Donec luctus ipsum eget quam tempus, nec blandit neque consectetur. Etiam ultrices velit eget enim viverra efficitur. Fusce mollis, lorem nec ornare pulvinar, sapien dolor semper massa, sit amet gravida nulla tellus volutpat dolor. Mauris iaculis ligula a finibus ullamcorper. Aenean sit amet nulla velit. Aliquam ut purus tempor, tempor felis sed, tempor ipsum.</p>
  <p>Donec mattis mattis porttitor. Ut auctor ultricies massa, ut commodo ipsum feugiat vitae. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas interdum, ex ac luctus varius, tellus augue suscipit metus, eu finibus metus turpis sed quam. Suspendisse ac eros in ex tristique iaculis quis eget lacus. Nunc et nibh ipsum. Pellentesque lacinia dui eget blandit ullamcorper. Nam in ex lacinia, pellentesque neque non, vehicula augue. Fusce semper elementum lacus vitae euismod. Sed placerat velit eu tortor faucibus fringilla. Aliquam auctor, nisi vel ultrices blandit, nunc arcu dapibus eros, quis lacinia ligula dui a est. In quis lacinia eros.</p>
</div>

app/views/layouts/_pagination.html.erb
<div class="d-flex justify-content-center">
  <%== pagy_bootstrap_nav(pagy) %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Auto Part V4" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-auto bg-dark-subtle sticky-top">
          <div class="d-flex flex-sm-column flex-row flex-nowrap align-items-center sticky-top">
            <%= render "layouts/shared/admin/navbar" %>
          </div>
        </div>
        <div class="col-sm p-3 min-vh-100">
          <%= render "layouts/shared/flash_messages" %>
          <%= yield %>
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Auto Part V4" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="d-flex flex-column min-vh-100">
      <%= render "layouts/shared/navbar" %>
      <div class="container">
        <%= render "layouts/shared/flash_messages" %>
        <%= yield %>
      </div>
      <%= render "layouts/shared/footer" %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/shared/_customer.html.erb
<div class="d-flex">
  <% if customer_signed_in? %>
    <div class="d-flex">
      <p class="mx-1 my-auto">
        <strong>Customer:</strong>
        <%= link_to current_customer.email, edit_customer_registration_path, class: "link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" %>
      </p>
      <%= link_to "Sign out", destroy_customer_session_path, class: "btn btn-primary mx-1", method: :delete, data: {turbo_method: :delete} %>
    </div>
  <% else %>
    <div class="d-flex">
      <%= link_to "Sign up", new_customer_registration_path, class: "btn btn-primary mx-1" %>
      <%= link_to "Sign in", new_customer_session_path, class: "btn btn-primary mx-1" %>
    </div>
  <% end %>
</div>

app/views/layouts/shared/_flash_messages.html.erb
<div class="my-2">
  <% if notice %>
    <div class="alert alert-success">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>
</div>

app/views/layouts/shared/_footer.html.erb
<footer class="bg-dark-subtle text-lg-start mt-auto">
  <div class="text-center">
    2024 Auto Part
  </div>
</footer>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark-subtle">
  <div class="container-fluid">
    <%= link_to "Auto part", root_path, class: "navbar-brand" %>
    <div class="me-auto">
      <ul class="navbar-nav">
        <li class="nav-item"> <%= link_to "Home", home_path, class: "nav-link" %> </li>
      </ul>
    </div>
    <%= render "layouts/shared/customer" %>
  </div>
</nav>

app/views/layouts/shared/admin/_admin.html.erb
<div>
  <li class="nav-item"><%= link_to current_admin.email, edit_admin_registration_path, class: "nav-link" %></li>
  <li class="nav-item"><%= link_to "sign out", destroy_admin_session_path, class: "nav-link", method: :delete, data: {turbo_method: :delete} %></li>
</div>

app/views/layouts/shared/admin/_navbar.html.erb
<nav class="navbar">
  <div class="m-1">
    <h4>Admin</h4>
    <ul class="nav nav-pills nav-flush flex-sm-column flex-row flex-nowrap mb-auto mx-auto">
      <%= render "layouts/shared/admin/admin" %>
      <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Customers", admin_customers_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Part Types", admin_part_types_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Car parts", admin_car_parts_path, class: "nav-link" %></li>
    </ul>
  </div>
</nav>